import React, { useEffect, useState } from 'react';
import { BarChart3, Box, Download, Film, Loader2, Plus, RefreshCw, Sparkles, X } from 'lucide-react';

type Tab = 'overview' | 'products' | 'campaigns' | 'library';
const request = async (url: string, init?: RequestInit) => { const response = await fetch(url, init); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'Error de servidor'); return data; };

export function WorkspacePanel({ isOpen, onClose, onOpenStudio }: { isOpen: boolean; onClose: () => void; onOpenStudio: () => void }) {
  const [tab, setTab] = useState<Tab>('overview'); const [data, setData] = useState<any>({}); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const [product, setProduct] = useState({ name: '', category: '', description: '', price: '' });
  const [campaign, setCampaign] = useState({ brief: '', platform: 'instagram', durationSeconds: 15 });
  const load = async () => { setLoading(true); setError(''); try { const [dashboard, products, campaigns, artifacts] = await Promise.all(['/api/workspace/dashboard','/api/workspace/products','/api/workspace/campaigns','/api/workspace/artifacts'].map(url => request(url))); setData({ dashboard, products, campaigns, artifacts }); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { if (isOpen) void load(); }, [isOpen]);
  if (!isOpen) return null;
  const createProduct = async (e: React.FormEvent) => { e.preventDefault(); try { await request('/api/workspace/products', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(product) }); setProduct({ name:'',category:'',description:'',price:'' }); await load(); } catch(e:any){setError(e.message);} };
  const createCampaign = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); try { await request('/api/campaign/prepare', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(campaign) }); setCampaign({ ...campaign, brief:'' }); await load(); } catch(e:any){setError(e.message);} finally{setLoading(false);} };
  const render = async (id: string) => { try { await request(`/api/workspace/campaigns/${id}/render`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ provider:'mock', idempotencyKey:crypto.randomUUID() }) }); await new Promise(r=>setTimeout(r,300)); await load(); } catch(e:any){setError(e.message);} };
  const nav = [{id:'overview',label:'Resumen',icon:BarChart3},{id:'products',label:'Productos',icon:Box},{id:'campaigns',label:'Campañas',icon:Film},{id:'library',label:'Biblioteca',icon:Download}] as const;
  return <div className="fixed inset-0 z-50 bg-zinc-950 text-white overflow-y-auto">
    <header className="sticky top-0 bg-zinc-950/90 backdrop-blur border-b border-zinc-800 p-4 flex justify-between z-10"><div><strong>ReelForge Workspace</strong><p className="text-xs text-zinc-500">Operación, campañas y consumo</p></div><div className="flex gap-2"><button onClick={load} className="p-2 rounded-lg bg-zinc-900"><RefreshCw className="w-4"/></button><button onClick={onClose} className="p-2 rounded-lg bg-zinc-900"><X className="w-4"/></button></div></header>
    <div className="max-w-7xl mx-auto p-4 md:p-8"><nav className="flex gap-2 overflow-x-auto mb-6">{nav.map(item=><button key={item.id} onClick={()=>setTab(item.id)} className={`px-4 py-2 rounded-xl flex items-center gap-2 text-sm ${tab===item.id?'bg-amber-400 text-zinc-950 font-bold':'bg-zinc-900'}`}><item.icon className="w-4"/>{item.label}</button>)}</nav>
    {error && <p className="mb-4 p-3 bg-red-500/10 border border-red-500/30 text-red-300 rounded-xl">{error}</p>}{loading && <Loader2 className="animate-spin text-amber-400"/>}
    {tab==='overview' && data.dashboard && <div className="space-y-6"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Productos',data.dashboard.counts.products],['Campañas',data.dashboard.counts.campaigns],['Videos listos',data.dashboard.counts.renders],['Costo API',`$${Number(data.dashboard.providerCostUsd).toFixed(2)}`]].map(([label,value])=><div key={String(label)} className="bg-zinc-900 border border-zinc-800 p-5 rounded-2xl"><p className="text-xs text-zinc-500">{label}</p><p className="text-3xl font-black mt-2">{value}</p></div>)}</div><div className="bg-zinc-900 border border-zinc-800 p-5 rounded-2xl"><div className="flex justify-between"><strong>Plan {data.dashboard.plan.name}</strong><span>{data.dashboard.usage.consumed + data.dashboard.usage.reserved}/{data.dashboard.usage.limit} videos</span></div><div className="h-3 bg-zinc-800 rounded-full mt-3 overflow-hidden"><div className="h-full bg-amber-400" style={{width:`${Math.min(100,(data.dashboard.usage.consumed+data.dashboard.usage.reserved)/data.dashboard.usage.limit*100)}%`}}/></div></div><button onClick={onOpenStudio} className="bg-amber-400 text-zinc-950 font-black px-6 py-3 rounded-xl flex gap-2"><Sparkles className="w-5"/>Abrir estudio creativo</button></div>}
    {tab==='products' && <div className="grid lg:grid-cols-3 gap-6"><form onSubmit={createProduct} className="bg-zinc-900 border border-zinc-800 p-5 rounded-2xl space-y-3"><h3 className="font-bold">Nuevo producto</h3>{(['name','category','description','price'] as const).map(key=><input key={key} required={key==='name'} placeholder={{name:'Nombre',category:'Categoría',description:'Descripción',price:'Precio'}[key]} className="w-full bg-zinc-950 border border-zinc-700 p-3 rounded-xl" value={product[key]} onChange={e=>setProduct({...product,[key]:e.target.value})}/>)}<button className="w-full bg-amber-400 text-zinc-950 font-bold py-2 rounded-xl flex justify-center gap-2"><Plus className="w-4"/>Agregar</button></form><div className="lg:col-span-2 grid sm:grid-cols-2 gap-3 content-start">{data.products?.map((p:any)=><div key={p.id} className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl"><strong>{p.name}</strong><p className="text-xs text-amber-400">{p.category} {p.price&&`· ${p.price}`}</p><p className="text-sm text-zinc-400 mt-2">{p.description}</p></div>)}</div></div>}
    {tab==='campaigns' && <div className="grid lg:grid-cols-3 gap-6"><form onSubmit={createCampaign} className="bg-zinc-900 border border-zinc-800 p-5 rounded-2xl space-y-3"><h3 className="font-bold">Campaña con agentes</h3><textarea required minLength={10} rows={7} placeholder="Objetivo, producto, oferta verificada y público…" className="w-full bg-zinc-950 border border-zinc-700 p-3 rounded-xl" value={campaign.brief} onChange={e=>setCampaign({...campaign,brief:e.target.value})}/><select className="w-full bg-zinc-950 border border-zinc-700 p-3 rounded-xl" value={campaign.platform} onChange={e=>setCampaign({...campaign,platform:e.target.value})}><option>instagram</option><option>facebook</option><option>tiktok</option></select><button className="w-full bg-amber-400 text-zinc-950 font-bold py-2 rounded-xl">Ejecutar swarm</button></form><div className="lg:col-span-2 space-y-3">{data.campaigns?.map((c:any)=><div key={c.id} className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl flex justify-between gap-4"><div><strong>{c.title}</strong><p className="text-xs text-zinc-500">{c.platform} · {c.duration_seconds}s</p><span className={`text-xs ${c.status==='approved'?'text-emerald-400':'text-amber-400'}`}>{c.status}</span></div><button disabled={c.status!=='approved'} onClick={()=>render(c.id)} className="px-3 py-2 bg-white text-zinc-950 rounded-lg text-xs font-bold disabled:opacity-30">Preparar render</button></div>)}</div></div>}
    {tab==='library' && <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{data.artifacts?.map((a:any)=><a key={a.id} href={a.url} target="_blank" className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl hover:border-amber-400"><Download className="w-5 text-amber-400"/><strong className="block mt-3">{a.campaign_title}</strong><p className="text-xs text-zinc-500">{a.kind} · {a.mime_type}</p></a>)}</div>}
    </div>
  </div>;
}
